-- MySQL Script generated by MySQL Workbench
-- Mon Aug  7 16:53:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Mega_Alianza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mega_Alianza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mega_Alianza` DEFAULT CHARACTER SET utf8 ;
USE `Mega_Alianza` ;

-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Clientes` (
  `id_Clientes` BIGINT(13) NULL,
  `Razon_social` VARCHAR(45) NULL,
  `Nombre_comercial` VARCHAR(45) NULL,
  `Telefono` BIGINT(13) NULL,
  `Ciudad` VARCHAR(15) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Persona_contacto` VARCHAR(45) NULL,
  `Telefono_p_contacto` BIGINT(13) NULL,
  `Estado` VARCHAR(10) NULL,
  PRIMARY KEY (`id_Clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Clientes_has_Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Clientes_has_Productos` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Clientes_has_Productos` (
  `id` INT NOT NULL,
  `Clientes_id_Clientes` BIGINT(13) NOT NULL,
  `Productos_id_Producto` INT NOT NULL,
  `Empleados_id_Empleados` BIGINT(13) NOT NULL,
  `Pedidos_Id_Pedido` INT NOT NULL,
  `Cantidad` SMALLINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Empleados` (
  `id_Empleados` BIGINT(13) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Celular` BIGINT(13) NULL,
  `Usuario` VARCHAR(20) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  `Ruta` VARCHAR(20) NULL,
  PRIMARY KEY (`id_Empleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Encuesta_satisfacción`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Encuesta_satisfacción` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Encuesta_satisfacción` (
  `Id_Encuesta_satisfacción` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Nombre_comercial` VARCHAR(45) NULL,
  `Nombre_contacto` VARCHAR(45) NULL,
  `Telefono_contacto` BIGINT(13) NULL,
  `Nombre_empleado` VARCHAR(45) NULL,
  `Conoce` VARCHAR(30) NULL,
  `Personal` VARCHAR(45) NULL,
  `Productos` VARCHAR(45) NULL,
  `Servicios` VARCHAR(45) NULL,
  `Observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`Id_Encuesta_satisfacción`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Formato_visitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Formato_visitas` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Formato_visitas` (
  `id_Formato_visitas` INT NOT NULL AUTO_INCREMENT,
  `Nit` BIGINT(13) NULL,
  `Direccion_mega` VARCHAR(45) NULL,
  `Telefono_mega` BIGINT(13) NULL,
  `Fecha` DATETIME NULL,
  `Nombre_empleado` VARCHAR(45) NULL,
  `Ruta` VARCHAR(10) NULL,
  `Razon_social` VARCHAR(45) NULL,
  `Nombre_comercial` VARCHAR(45) NULL,
  `Telefono` BIGINT(13) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Cliente_nuevo` VARCHAR(20) NULL,
  `Observaciones` VARCHAR(200) NULL,
  `Prueba` BLOB NULL,
  PRIMARY KEY (`id_Formato_visitas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Pedidos` (
  `Id_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL,
  `id_cliente` BIGINT(13) NULL,
  `Id_empleado` BIGINT(13) NULL,
  `Descripción` VARCHAR(60) NULL,
  `Precio` DECIMAL NULL,
  `Observaciones` VARCHAR(200) NULL,
  `Estado` VARCHAR(30) NULL,
  PRIMARY KEY (`Id_Pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mega_Alianza`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mega_Alianza`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Mega_Alianza`.`Productos` (
  `id_Producto` INT NOT NULL,
  `Descripcion` VARCHAR(60) NULL,
  `Grupo_inventario` VARCHAR(30) NULL,
  `Precio` DECIMAL NULL,
  PRIMARY KEY (`id_Producto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
